{
  "language": "java",
  "id": "commons-lang-ExceptionUtils_464",
  "buggyPath": ".",
  "referencePath": null,
  "buildCommand": "mvn package -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true -Drat.numUnapprovedLicenses=100 -DskipTests=true -DskipITs=true -Dtest=None -DfailIfNoTests=false",
  "testCommand": "mvn clean test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true -Drat.numUnapprovedLicenses=100",
  "categories": [
    "safety",
    "npe"
  ],
  "npe": {
    "filepath": "src/main/java/org/apache/commons/lang3/exception/ExceptionUtils.java",
    "line": 490,
    "npe_method": "printRootCauseStackTrace",
    "deref_field": "stream",
    "npe_class": "ExceptionUtils",
    "repo": "commons-lang",
    "bug_id": "ExceptionUtils_464"
  }
}
